### ISSUE TITLE
issue on line 16

### ISSUE THREAD

**Issue by TheSpaceArmy** [StoneWaves/Beam-Status#1]
Warning: file_get_contents(http://beam.pro/api/v1/channels/): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in /home/thespac3/public_html/blog/wp-content/plugins/Beam-Status-master/beam-status.php on line 16

**Comment by StoneWaves** [comment]
This error is only applicable when you haven't configured the plugin on the admin screen.
Once you enter a valid streamer this error will go away.
