### ISSUE TITLE
Beam-Status Query

### ISSUE THREAD

**Issue by Skavenger0** [StoneWaves/Beam-Status#2]
Hi guys,

Does this plugin still work. Trying to give it a go but its not showing on the webpage. Where should it display?

**Comment by StoneWaves** [comment]
Hi,  

This project was semi abandoned but I have updated it to work with the new mixer domain.
Try the latest release and see if it works for you now.

It should display in the top right of your site, I think

**Comment by Skavenger0** [comment]
Ye I gathered it was abandoned, wasnt sure what i should be looking for, ill have a play and see if I can get it working and feed back accordingly

**Comment by StoneWaves** [comment]
Good luck.
If you can't find something that works for you and there's interest I'll do a rewrite and get some input from you.
